-- todo 테이블 생성
CREATE TABLE TBL_TODO (
NO NUMBER(5) PRIMARY KEY,
ALLDAY CHAR(1) NOT NULL CHECK (allday='0' or allday='1'),
FROM_DATE DATE NOT NULL,
TO_DATE DATE NOT NULL,
TITLE VARCHAR2(100) NOT NULL,
CONTENT VARCHAR2(100)
--ACOUNT NUMBER(5) REFERENCE(TBL_ACCOUNT.NO) NOT NULL
);

--TODO 시퀀스 생성
CREATE SEQUENCE SEQ_TODO;

-- ANNIVERSARY 테이블 생성
CREATE TABLE TBL_ANNIVERSARY(
NO NUMBER(5) PRIMARY KEY,
MONTH NUMBER(2) NOT NULL,
DAY NUMBER(2) NOT NULL,
TITLE VARCHAR2(100) NOT NULL,
KIND VARCHAR2(50) CHECK(KIND IN('HOLIDAY', 'BIRTHDAY'))
--ACCOUNT NUMBER(5) REFERENCT(TBL_ACCOUNT.NO) NOT NULL
);

--ANNIVERSARY 시퀀스 생성
CREATE SEQUENCE SEQ_ANNIVERSARY;


-- 외래키 등록
alter table tbl_todo add account_no number(5) REFERENCES tbl_account(no) on delete cascade not null;
alter table tbl_anniversary add account_no number(5) REFERENCES tbl_account(no) on delete cascade not null;

